PROGRAM TEST_Z85

USE ZMQ
USE ASSERT
IMPLICIT NONE

LOGICAL :: RESULT
CHARACTER(KIND = C_CHAR, LEN = 8), TARGET :: ACTUAL_DECODED
CHARACTER(KIND = C_CHAR, LEN = 8), TARGET :: EXPECTED_DECODED
CHARACTER(KIND = C_CHAR, LEN = 11) :: ACTUAL_ENCODED
CHARACTER(KIND = C_CHAR, LEN = 11) :: EXPECTED_ENCODED

EXPECTED_DECODED(1:1) = CHAR(134)
EXPECTED_DECODED(2:2) = CHAR( 79)
EXPECTED_DECODED(3:3) = CHAR(210)
EXPECTED_DECODED(4:4) = CHAR(111)
EXPECTED_DECODED(5:5) = CHAR(181)
EXPECTED_DECODED(6:6) = CHAR( 89)
EXPECTED_DECODED(7:7) = CHAR(247)
EXPECTED_DECODED(8:8) = CHAR( 91)
EXPECTED_ENCODED = 'HelloWorld' // C_NULL_CHAR

RESULT = ZMQ_Z85_ENCODE(ACTUAL_ENCODED, C_LOC(EXPECTED_DECODED), 8_C_SIZE_T)
CALL ASSERT_TRUE(RESULT)
CALL ASSERT_TRUE(ACTUAL_ENCODED == EXPECTED_ENCODED)

RESULT = ZMQ_Z85_DECODE(C_LOC(ACTUAL_DECODED), EXPECTED_ENCODED)
CALL ASSERT_TRUE(RESULT)
CALL ASSERT_TRUE(ACTUAL_DECODED == EXPECTED_DECODED)

END PROGRAM
