PROGRAM TEST_VERSION

USE ZMQ
USE ASSERT
IMPLICIT NONE

INTEGER(KIND = C_INT) :: MAJOR
INTEGER(KIND = C_INT) :: MINOR
INTEGER(KIND = C_INT) :: PATCH

CALL ZMQ_VERSION(MAJOR, MINOR, PATCH)
CALL ASSERT_TRUE(MAJOR == 4)
CALL ASSERT_TRUE(MINOR >= 1)
CALL ASSERT_TRUE(PATCH >= 0)

CALL FZMQ_VERSION(MAJOR, MINOR, PATCH)
CALL ASSERT_TRUE(MAJOR == FZMQ_VERSION_MAJOR)
CALL ASSERT_TRUE(MINOR == FZMQ_VERSION_MINOR)
CALL ASSERT_TRUE(PATCH == FZMQ_VERSION_PATCH)

END PROGRAM
