PROGRAM TEST_CONTEXT_DEPRACATED

USE ZMQ
USE ASSERT
IMPLICIT NONE

TYPE(C_PTR) :: CONTEXT
INTEGER(KIND = C_INT) :: CODE

CONTEXT = ZMQ_INIT(1)

CODE = ZMQ_CTX_DESTROY(CONTEXT)
CALL ASSERT_EQUALS(0, CODE)

CONTEXT = ZMQ_INIT(1)

CODE = ZMQ_TERM(CONTEXT)
CALL ASSERT_EQUALS(0, CODE)

END PROGRAM
