PROGRAM TEST_MESSAGE

USE, INTRINSIC :: ISO_C_BINDING
USE ZMQ
USE ASSERT
IMPLICIT NONE

TYPE(C_PTR) :: DATA
TYPE(ZMQ_MSG_T) :: MESSAGE
TYPE(ZMQ_MSG_T) :: COPIED
TYPE(ZMQ_MSG_T) :: MOVED
INTEGER(KIND = C_INT) :: CODE
INTEGER(KIND = C_INT) :: SIZE

CODE = ZMQ_MSG_INIT_SIZE(MESSAGE, 8_C_SIZE_T)
CALL ASSERT_EQUALS(0, CODE)
CODE = ZMQ_MSG_INIT(COPIED)
CALL ASSERT_EQUALS(0, CODE)
CODE = ZMQ_MSG_INIT(MOVED)
CALL ASSERT_EQUALS(0, CODE)
SIZE = ZMQ_MSG_SIZE(MESSAGE)
CALL ASSERT_EQUALS(8, SIZE)

CODE = ZMQ_MSG_COPY(COPIED, MESSAGE)
CALL ASSERT_EQUALS(0, CODE)
SIZE = ZMQ_MSG_SIZE(COPIED)
CALL ASSERT_EQUALS(8, SIZE)

CODE = ZMQ_MSG_MOVE(MOVED, COPIED)
CALL ASSERT_EQUALS(0, CODE)
SIZE = ZMQ_MSG_SIZE(COPIED)
CALL ASSERT_EQUALS(0, SIZE)
SIZE = ZMQ_MSG_SIZE(MOVED)
CALL ASSERT_EQUALS(8, SIZE)

CODE = ZMQ_MSG_CLOSE(MESSAGE)
CALL ASSERT_EQUALS(0, CODE)
CODE = ZMQ_MSG_CLOSE(COPIED)
CALL ASSERT_EQUALS(0, CODE)
CODE = ZMQ_MSG_CLOSE(MOVED)
CALL ASSERT_EQUALS(0, CODE)

END PROGRAM
