PROGRAM TEST_SOCKET

USE ZMQ
USE ASSERT
IMPLICIT NONE

TYPE(C_PTR) :: CONTEXT
TYPE(C_PTR) :: SOCKET
INTEGER(KIND = C_INT) :: CODE
INTEGER(KIND = C_INT) :: IOPT

CONTEXT = ZMQ_CTX_NEW()

SOCKET = ZMQ_SOCKET(CONTEXT, ZMQ_PAIR)
CODE = ZMQ_CONNECT(SOCKET, 'inproc://fzmq')
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_SETSOCKOPT(SOCKET, ZMQ_RCVHWM, 500)
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_GETSOCKOPT(SOCKET, ZMQ_RCVHWM, IOPT)
CALL ASSERT_EQUALS(0, CODE)
CALL ASSERT_EQUALS(500, IOPT)

CODE = ZMQ_DISCONNECT(SOCKET, 'inproc://fzmq')
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_CLOSE(SOCKET)
CALL ASSERT_EQUALS(0, CODE)

SOCKET = ZMQ_SOCKET(CONTEXT, ZMQ_PAIR)
CODE = ZMQ_BIND(SOCKET, 'inproc://fzmq')
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_UNBIND(SOCKET, 'inproc://fzmq')
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_CLOSE(SOCKET)
CALL ASSERT_EQUALS(0, CODE)

CODE = ZMQ_CTX_TERM(CONTEXT)
CALL ASSERT_EQUALS(0, CODE)

END PROGRAM
