MODULE ZMQ

  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  TYPE, BIND(C) :: ZMQ_EVENT_T
    INTEGER(KIND = C_INT16_T) :: EVENT
    INTEGER(KIND = C_INT32_T) :: VALUE
  END TYPE ZMQ_EVENT_T

  TYPE, BIND(C) :: ZMQ_MSG_T
    INTEGER(KIND = C_SIGNED_CHAR), DIMENSION(64) :: D
  END TYPE ZMQ_MSG_T

  TYPE, BIND(C) :: ZMQ_POLLITEM_T
    TYPE(C_PTR) :: SOCKET
    INTEGER(KIND = C_INT) :: FD
    INTEGER(KIND = C_SHORT) :: EVENTS
    INTEGER(KIND = C_SHORT) :: REVENTS
  END TYPE ZMQ_POLLITEM_T

  ! CONTEXT OPTIONS
  INTEGER, PARAMETER :: ZMQ_IO_THREADS = 1
  INTEGER, PARAMETER :: ZMQ_MAX_SOCKETS = 2
  INTEGER, PARAMETER :: ZMQ_SOCKET_LIMIT = 3
  INTEGER, PARAMETER :: ZMQ_THREAD_PRIORITY = 3
  INTEGER, PARAMETER :: ZMQ_THREAD_SCHED_POLICY = 4

  ! CONTEXT DEFAULTS
  INTEGER, PARAMETER :: ZMQ_IO_THREADS_DFLT = 1
  INTEGER, PARAMETER :: ZMQ_MAX_SOCKETS_DFLT = 1023
  INTEGER, PARAMETER :: ZMQ_THREAD_PRIORITY_DFLT = -1
  INTEGER, PARAMETER :: ZMQ_THREAD_SCHED_POLICY_DFLT = -1

  ! SOCKET TYPES
  INTEGER, PARAMETER :: ZMQ_PAIR = 0
  INTEGER, PARAMETER :: ZMQ_PUB = 1
  INTEGER, PARAMETER :: ZMQ_SUB = 2
  INTEGER, PARAMETER :: ZMQ_REQ = 3
  INTEGER, PARAMETER :: ZMQ_REP = 4
  INTEGER, PARAMETER :: ZMQ_DEALER = 5
  INTEGER, PARAMETER :: ZMQ_ROUTER = 6
  INTEGER, PARAMETER :: ZMQ_PULL = 7
  INTEGER, PARAMETER :: ZMQ_PUSH = 8
  INTEGER, PARAMETER :: ZMQ_XPUB = 9
  INTEGER, PARAMETER :: ZMQ_XSUB = 10
  INTEGER, PARAMETER :: ZMQ_STREAM = 11

  ! SOCKET OPTIONS
  INTEGER, PARAMETER :: ZMQ_AFFINITY = 4
  INTEGER, PARAMETER :: ZMQ_IDENTITY = 5
  INTEGER, PARAMETER :: ZMQ_SUBSCRIBE = 6
  INTEGER, PARAMETER :: ZMQ_UNSUBSCRIBE = 7
  INTEGER, PARAMETER :: ZMQ_RATE = 8
  INTEGER, PARAMETER :: ZMQ_RECOVERY_IVL = 9
  INTEGER, PARAMETER :: ZMQ_SNDBUF = 11
  INTEGER, PARAMETER :: ZMQ_RCVBUF = 12
  INTEGER, PARAMETER :: ZMQ_RCVMORE = 13
  INTEGER, PARAMETER :: ZMQ_FD = 14
  INTEGER, PARAMETER :: ZMQ_EVENTS = 15
  INTEGER, PARAMETER :: ZMQ_TYPE = 16
  INTEGER, PARAMETER :: ZMQ_LINGER = 17
  INTEGER, PARAMETER :: ZMQ_RECONNECT_IVL = 18
  INTEGER, PARAMETER :: ZMQ_BACKLOG = 19
  INTEGER, PARAMETER :: ZMQ_RECONNECT_IVL_MAX = 21
  INTEGER, PARAMETER :: ZMQ_MAXMSGSIZE = 22
  INTEGER, PARAMETER :: ZMQ_SNDHWM = 23
  INTEGER, PARAMETER :: ZMQ_RCVHWM = 24
  INTEGER, PARAMETER :: ZMQ_MULTICAST_HOPS = 25
  INTEGER, PARAMETER :: ZMQ_RCVTIMEO = 27
  INTEGER, PARAMETER :: ZMQ_SNDTIMEO = 28
  INTEGER, PARAMETER :: ZMQ_LAST_ENDPOINT = 32
  INTEGER, PARAMETER :: ZMQ_ROUTER_MANDATORY = 33
  INTEGER, PARAMETER :: ZMQ_TCP_KEEPALIVE = 34
  INTEGER, PARAMETER :: ZMQ_TCP_KEEPALIVE_CNT = 35
  INTEGER, PARAMETER :: ZMQ_TCP_KEEPALIVE_IDLE = 36
  INTEGER, PARAMETER :: ZMQ_TCP_KEEPALIVE_INTVL = 37
  INTEGER, PARAMETER :: ZMQ_IMMEDIATE = 39
  INTEGER, PARAMETER :: ZMQ_XPUB_VERBOSE = 40
  INTEGER, PARAMETER :: ZMQ_ROUTER_RAW = 41
  INTEGER, PARAMETER :: ZMQ_IPV6 = 42
  INTEGER, PARAMETER :: ZMQ_MECHANISM = 43
  INTEGER, PARAMETER :: ZMQ_PLAIN_SERVER = 44
  INTEGER, PARAMETER :: ZMQ_PLAIN_USERNAME = 45
  INTEGER, PARAMETER :: ZMQ_PLAIN_PASSWORD = 46
  INTEGER, PARAMETER :: ZMQ_CURVE_SERVER = 47
  INTEGER, PARAMETER :: ZMQ_CURVE_PUBLICKEY = 48
  INTEGER, PARAMETER :: ZMQ_CURVE_SECRETKEY = 49
  INTEGER, PARAMETER :: ZMQ_CURVE_SERVERKEY = 50
  INTEGER, PARAMETER :: ZMQ_PROBE_ROUTER = 51
  INTEGER, PARAMETER :: ZMQ_REQ_CORRELATE = 52
  INTEGER, PARAMETER :: ZMQ_REQ_RELAXED = 53
  INTEGER, PARAMETER :: ZMQ_CONFLATE = 54
  INTEGER, PARAMETER :: ZMQ_ZAP_DOMAIN = 55
  INTEGER, PARAMETER :: ZMQ_ROUTER_HANDOVER = 56
  INTEGER, PARAMETER :: ZMQ_TOS = 57
  INTEGER, PARAMETER :: ZMQ_CONNECT_RID = 61
  INTEGER, PARAMETER :: ZMQ_GSSAPI_SERVER = 62
  INTEGER, PARAMETER :: ZMQ_GSSAPI_PRINCIPAL = 63
  INTEGER, PARAMETER :: ZMQ_GSSAPI_SERVICE_PRINCIPAL = 64
  INTEGER, PARAMETER :: ZMQ_GSSAPI_PLAINTEXT = 65
  INTEGER, PARAMETER :: ZMQ_HANDSHAKE_IVL = 66
  INTEGER, PARAMETER :: ZMQ_SOCKS_PROXY = 68
  INTEGER, PARAMETER :: ZMQ_XPUB_NODROP = 69

  ! MESSAGE OPTIONS
  INTEGER, PARAMETER :: ZMQ_MORE = 1
  INTEGER, PARAMETER :: ZMQ_SRCFD = 2
  INTEGER, PARAMETER :: ZMQ_SHARED = 3

  ! SEND/RECV OPTIONS
  INTEGER, PARAMETER :: ZMQ_DONTWAIT = 1
  INTEGER, PARAMETER :: ZMQ_SNDMORE = 2

  ! SECURITY MECHANISMS
  INTEGER, PARAMETER :: ZMQ_NULL = 0
  INTEGER, PARAMETER :: ZMQ_PLAIN = 1
  INTEGER, PARAMETER :: ZMQ_CURVE = 2
  INTEGER, PARAMETER :: ZMQ_GSSAPI = 3

  ! EVENTS
  INTEGER, PARAMETER :: ZMQ_EVENT_CONNECTED = 1
  INTEGER, PARAMETER :: ZMQ_EVENT_CONNECT_DELAYED = 2
  INTEGER, PARAMETER :: ZMQ_EVENT_CONNECT_RETRIED = 4
  INTEGER, PARAMETER :: ZMQ_EVENT_LISTENING = 8
  INTEGER, PARAMETER :: ZMQ_EVENT_BIND_FAILED = 16
  INTEGER, PARAMETER :: ZMQ_EVENT_ACCEPTED = 32
  INTEGER, PARAMETER :: ZMQ_EVENT_ACCEPT_FAILED = 64
  INTEGER, PARAMETER :: ZMQ_EVENT_CLOSED = 128
  INTEGER, PARAMETER :: ZMQ_EVENT_CLOSE_FAILED = 256
  INTEGER, PARAMETER :: ZMQ_EVENT_DISCONNECTED = 512
  INTEGER, PARAMETER :: ZMQ_EVENT_MONITOR_STOPPED = 1024
  INTEGER, PARAMETER :: ZMQ_EVENT_ALL = 65535

  ! POLLING OPTIONS
  INTEGER, PARAMETER :: ZMQ_POLLIN = 1
  INTEGER, PARAMETER :: ZMQ_POLLOUT = 2
  INTEGER, PARAMETER :: ZMQ_POLLERR = 4

  ! PROBE CAPABILITIES
  INTEGER, PARAMETER :: ZMQ_HAS_CAPABILITIES = 1

  INTERFACE

    FUNCTION ZMQ_CLOSE(SOCKET) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      INTEGER(KIND = C_INT) :: ZMQ_CLOSE
    END FUNCTION ZMQ_CLOSE

    FUNCTION ZMQ_CTX_DESTROY(CONTEXT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT) :: ZMQ_CTX_DESTROY
    END FUNCTION ZMQ_CTX_DESTROY

    FUNCTION ZMQ_CTX_GET(CONTEXT, OPTION_NAME) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
      INTEGER(KIND = C_INT) :: ZMQ_CTX_GET
    END FUNCTION ZMQ_CTX_GET

    FUNCTION ZMQ_CTX_NEW() BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_PTR
      IMPLICIT NONE
      TYPE(C_PTR) :: ZMQ_CTX_NEW
    END FUNCTION ZMQ_CTX_NEW

    FUNCTION ZMQ_CTX_SET(CONTEXT, OPTION_NAME, OPTION_VALUE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_VALUE
      INTEGER(KIND = C_INT) :: ZMQ_CTX_SET
    END FUNCTION ZMQ_CTX_SET

    FUNCTION ZMQ_CTX_SHUTDOWN(CONTEXT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT) :: ZMQ_CTX_SHUTDOWN
    END FUNCTION ZMQ_CTX_SHUTDOWN

    FUNCTION ZMQ_CTX_TERM(CONTEXT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT) :: ZMQ_CTX_TERM
    END FUNCTION ZMQ_CTX_TERM

    FUNCTION ZMQ_CURVE_KEYPAIR(Z85_PUBLIC_KEY, Z85_SECRET_KEY) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_INT
      IMPLICIT NONE
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(OUT) :: Z85_PUBLIC_KEY
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(OUT) :: Z85_SECRET_KEY
      INTEGER(KIND = C_INT) :: ZMQ_CURVE_KEYPAIR
    END FUNCTION ZMQ_CURVE_KEYPAIR

    FUNCTION ZMQ_ERRNO() BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPLICIT NONE
      INTEGER(KIND = C_INT) :: ZMQ_ERRNO
    END FUNCTION ZMQ_ERRNO

    FUNCTION ZMQ_INIT(IO_THREADS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_PTR, C_INT
      IMPLICIT NONE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: IO_THREADS
      TYPE(C_PTR) :: ZMQ_INIT
    END FUNCTION ZMQ_INIT

    FUNCTION ZMQ_MSG_CLOSE(MESSAGE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT) :: ZMQ_MSG_CLOSE
    END FUNCTION ZMQ_MSG_CLOSE

    FUNCTION ZMQ_MSG_COPY(DEST, SRC) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: DEST
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: SRC
      INTEGER(KIND = C_INT) :: ZMQ_MSG_COPY
    END FUNCTION ZMQ_MSG_COPY

    FUNCTION ZMQ_MSG_DATA(MESSAGE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_PTR
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      TYPE(C_PTR) :: ZMQ_MSG_DATA
    END FUNCTION ZMQ_MSG_DATA

    FUNCTION ZMQ_MSG_GET(MESSAGE, PROPERTY) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: PROPERTY
      INTEGER(KIND = C_INT) :: ZMQ_MSG_GET
    END FUNCTION ZMQ_MSG_GET

    FUNCTION ZMQ_MSG_INIT(MESSAGE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT) :: ZMQ_MSG_INIT
    END FUNCTION ZMQ_MSG_INIT

    FUNCTION ZMQ_MSG_INIT_DATA(MESSAGE, DATA, SIZE, FFN, HINT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_FUNPTR, C_INT, C_PTR, C_SIZE_T
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      TYPE(C_PTR), VALUE, INTENT(IN) :: DATA
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: SIZE
      TYPE(C_FUNPTR), VALUE, INTENT(IN) :: FFN
      TYPE(C_PTR), VALUE, INTENT(IN) :: HINT
      INTEGER(KIND = C_INT) :: ZMQ_MSG_INIT_DATA
    END FUNCTION ZMQ_MSG_INIT_DATA

    FUNCTION ZMQ_MSG_INIT_SIZE(MESSAGE, SIZE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_SIZE_T
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: SIZE
      INTEGER(KIND = C_INT) :: ZMQ_MSG_INIT_SIZE
    END FUNCTION ZMQ_MSG_INIT_SIZE

    FUNCTION ZMQ_MSG_MORE(MESSAGE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT) :: ZMQ_MSG_MORE
    END FUNCTION ZMQ_MSG_MORE

    FUNCTION ZMQ_MSG_MOVE(DEST, SRC) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: DEST
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: SRC
      INTEGER(KIND = C_INT) :: ZMQ_MSG_MOVE
    END FUNCTION ZMQ_MSG_MOVE

    FUNCTION ZMQ_MSG_RECV(MESSAGE, SOCKET, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_MSG_RECV
    END FUNCTION ZMQ_MSG_RECV

    FUNCTION ZMQ_MSG_SEND(MESSAGE, SOCKET, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_MSG_SEND
    END FUNCTION ZMQ_MSG_SEND

    FUNCTION ZMQ_MSG_SET(MESSAGE, PROPERTY, VALUE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: PROPERTY
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: VALUE
      INTEGER(KIND = C_INT) :: ZMQ_MSG_SET
    END FUNCTION ZMQ_MSG_SET

    FUNCTION ZMQ_MSG_SIZE(MESSAGE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_SIZE_T
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_SIZE_T) :: ZMQ_MSG_SIZE
    END FUNCTION ZMQ_MSG_SIZE

    FUNCTION ZMQ_POLL(ITEMS, NITEMS, TIMEOUT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_LONG
      IMPORT :: ZMQ_POLLITEM_T
      IMPLICIT NONE
      TYPE(ZMQ_POLLITEM_T), DIMENSION(*), INTENT(INOUT) :: ITEMS
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: NITEMS
      INTEGER(KIND = C_LONG), VALUE, INTENT(IN) :: TIMEOUT
      INTEGER(KIND = C_INT) :: ZMQ_POLL
    END FUNCTION ZMQ_POLL

    FUNCTION ZMQ_PROXY(FRONTEND, BACKEND, CAPTURE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: FRONTEND
      TYPE(C_PTR), VALUE, INTENT(IN) :: BACKEND
      TYPE(C_PTR), VALUE, INTENT(IN) :: CAPTURE
      INTEGER(KIND = C_INT) :: ZMQ_PROXY
    END FUNCTION ZMQ_PROXY

    FUNCTION ZMQ_PROXY_STEERABLE(FRONTEND, BACKEND, CAPTURE, CONTROL) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: FRONTEND
      TYPE(C_PTR), VALUE, INTENT(IN) :: BACKEND
      TYPE(C_PTR), VALUE, INTENT(IN) :: CAPTURE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTROL
      INTEGER(KIND = C_INT) :: ZMQ_PROXY_STEERABLE
    END FUNCTION ZMQ_PROXY_STEERABLE

    FUNCTION ZMQ_RECV(SOCKET, BUF, LEN, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR, C_SIZE_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(C_PTR), VALUE, INTENT(IN) :: BUF
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: LEN
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_RECV
    END FUNCTION ZMQ_RECV

    FUNCTION ZMQ_RECVMSG(SOCKET, MESSAGE, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_RECVMSG
    END FUNCTION ZMQ_RECVMSG

    FUNCTION ZMQ_SEND(SOCKET, BUF, LEN, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR, C_SIZE_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(C_PTR), VALUE, INTENT(IN) :: BUF
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: LEN
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_SEND
    END FUNCTION ZMQ_SEND

    FUNCTION ZMQ_SEND_CONST(SOCKET, BUF, LEN, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR, C_SIZE_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(C_PTR), VALUE, INTENT(IN) :: BUF
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: LEN
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_SEND_CONST
    END FUNCTION ZMQ_SEND_CONST

    FUNCTION ZMQ_SENDMSG(SOCKET, MESSAGE, FLAGS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPORT :: ZMQ_MSG_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(ZMQ_MSG_T), INTENT(INOUT) :: MESSAGE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: FLAGS
      INTEGER(KIND = C_INT) :: ZMQ_SENDMSG
    END FUNCTION ZMQ_SENDMSG

    FUNCTION ZMQ_SOCKET(CONTEXT, TYPE_) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: TYPE_
      TYPE(C_PTR) :: ZMQ_SOCKET
    END FUNCTION ZMQ_SOCKET

    FUNCTION ZMQ_SOCKET_MONITOR(SOCKET, ADDR, EVENTS) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      TYPE(C_PTR), VALUE, INTENT(IN) :: ADDR
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: EVENTS
      INTEGER(KIND = C_INT) :: ZMQ_SOCKET_MONITOR
    END FUNCTION ZMQ_SOCKET_MONITOR

    FUNCTION ZMQ_TERM(CONTEXT) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: CONTEXT
      INTEGER(KIND = C_INT) :: ZMQ_TERM
    END FUNCTION ZMQ_TERM

    SUBROUTINE ZMQ_VERSION(MAJOR, MINOR, PATCH) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT
      IMPLICIT NONE
      INTEGER(KIND = C_INT), INTENT(OUT) :: MAJOR
      INTEGER(KIND = C_INT), INTENT(OUT) :: MINOR
      INTEGER(KIND = C_INT), INTENT(OUT) :: PATCH
    END SUBROUTINE ZMQ_VERSION

    FUNCTION ZMQ_Z85_DECODE(DEST, STRING) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: DEST
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(IN) :: STRING
      TYPE(C_PTR) :: ZMQ_Z85_DECODE
    END FUNCTION ZMQ_Z85_DECODE

    FUNCTION ZMQ_Z85_ENCODE(DEST, DATA, SIZE) BIND(C)
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_PTR, C_SIZE_T
      IMPLICIT NONE
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(OUT) :: DEST
      TYPE(C_PTR), VALUE, INTENT(IN) :: DATA
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: SIZE
      TYPE(C_PTR) :: ZMQ_Z85_ENCODE
    END FUNCTION ZMQ_Z85_ENCODE

    FUNCTION FZMQ_BIND(SOCKET, ENDPOINT) BIND(C, NAME = 'zmq_bind')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(IN) :: ENDPOINT
      INTEGER(KIND = C_INT) :: FZMQ_BIND
    END FUNCTION FZMQ_BIND

    FUNCTION FZMQ_CONNECT(SOCKET, ENDPOINT) BIND(C, NAME = 'zmq_connect')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(IN) :: ENDPOINT
      INTEGER(KIND = C_INT) :: FZMQ_CONNECT
    END FUNCTION FZMQ_CONNECT

    FUNCTION FZMQ_DISCONNECT(SOCKET, ENDPOINT) BIND(C, NAME = 'zmq_disconnect')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(IN) :: ENDPOINT
      INTEGER(KIND = C_INT) :: FZMQ_DISCONNECT
    END FUNCTION FZMQ_DISCONNECT

    FUNCTION FZMQ_GETSOCKOPT(SOCKET, OPTION_NAME, OPTION_VALUE, OPTION_LEN) &
        BIND(C, NAME = 'zmq_getsockopt')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR, C_SIZE_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
      TYPE(C_PTR), VALUE, INTENT(IN) :: OPTION_VALUE
      INTEGER(KIND = C_SIZE_T), INTENT(INOUT) :: OPTION_LEN
      INTEGER(KIND = C_INT) :: FZMQ_GETSOCKOPT
    END FUNCTION FZMQ_GETSOCKOPT

    FUNCTION FZMQ_SETSOCKOPT(SOCKET, OPTION_NAME, OPTION_VALUE, OPTION_LEN) &
        BIND(C, NAME = 'zmq_setsockopt')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR, C_SIZE_T
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
      TYPE(C_PTR), VALUE, INTENT(IN) :: OPTION_VALUE
      INTEGER(KIND = C_SIZE_T), VALUE, INTENT(IN) :: OPTION_LEN
      INTEGER(KIND = C_INT) :: FZMQ_SETSOCKOPT
    END FUNCTION FZMQ_SETSOCKOPT

    FUNCTION FZMQ_STRERROR(ERRNUM) BIND(C, NAME = 'zmq_strerror')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_PTR
      IMPLICIT NONE
      INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: ERRNUM
      TYPE(C_PTR) :: FZMQ_STRERROR
    END FUNCTION FZMQ_STRERROR

    FUNCTION FZMQ_UNBIND(SOCKET, ENDPOINT) BIND(C, NAME = 'zmq_unbind')
      USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_CHAR, C_INT, C_PTR
      IMPLICIT NONE
      TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
      CHARACTER(KIND = C_CHAR), DIMENSION(*), INTENT(IN) :: ENDPOINT
      INTEGER(KIND = C_INT) :: FZMQ_UNBIND
    END FUNCTION FZMQ_UNBIND

  END INTERFACE

  INTERFACE ZMQ_GETSOCKOPT
    MODULE PROCEDURE ZMQ_GETSOCKOPT_INT, &
                     ZMQ_GETSOCKOPT_INT64, &
                     ZMQ_GETSOCKOPT_STR
  END INTERFACE ZMQ_GETSOCKOPT

  INTERFACE ZMQ_SETSOCKOPT
    MODULE PROCEDURE ZMQ_SETSOCKOPT_INT, &
                     ZMQ_SETSOCKOPT_INT64, &
                     ZMQ_SETSOCKOPT_STR
  END INTERFACE ZMQ_SETSOCKOPT

CONTAINS

  FUNCTION ZMQ_BIND(SOCKET, ENDPOINT) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    CHARACTER(LEN = *), INTENT(IN) :: ENDPOINT
    INTEGER(KIND = C_INT) :: CODE

    CODE = FZMQ_BIND(SOCKET, TRIM(ENDPOINT) // C_NULL_CHAR)
  END FUNCTION ZMQ_BIND

  FUNCTION ZMQ_CONNECT(SOCKET, ENDPOINT) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    CHARACTER(LEN = *), INTENT(IN) :: ENDPOINT
    INTEGER(KIND = C_INT) :: CODE

    CODE = FZMQ_CONNECT(SOCKET, TRIM(ENDPOINT) // C_NULL_CHAR)
  END FUNCTION ZMQ_CONNECT

  FUNCTION ZMQ_DISCONNECT(SOCKET, ENDPOINT) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    CHARACTER(LEN = *), INTENT(IN) :: ENDPOINT
    INTEGER(KIND = C_INT) :: CODE

    CODE = FZMQ_DISCONNECT(SOCKET, TRIM(ENDPOINT) // C_NULL_CHAR)
  END FUNCTION ZMQ_DISCONNECT

  FUNCTION ZMQ_GETSOCKOPT_INT(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    INTEGER(KIND = C_INT), INTENT(OUT) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    INTEGER(KIND = C_INT), TARGET :: OPTION_VAL

    OPTION_LEN = C_SIZEOF(OPTION_VAL)
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_GETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
    OPTION_VALUE = OPTION_VAL
  END FUNCTION ZMQ_GETSOCKOPT_INT

  FUNCTION ZMQ_GETSOCKOPT_INT64(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    INTEGER(KIND = C_INT64_T), INTENT(OUT) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    INTEGER(KIND = C_INT64_T), TARGET :: OPTION_VAL

    OPTION_LEN = C_SIZEOF(OPTION_VAL)
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_GETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
    OPTION_VALUE = OPTION_VAL
  END FUNCTION ZMQ_GETSOCKOPT_INT64

  FUNCTION ZMQ_GETSOCKOPT_STR(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    CHARACTER(LEN = *), INTENT(INOUT) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    INTEGER :: EOS
    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    CHARACTER(LEN = :), ALLOCATABLE, TARGET :: OPTION_VAL

    OPTION_LEN = LEN(OPTION_VALUE) + 1
    ALLOCATE(CHARACTER(LEN = OPTION_LEN) :: OPTION_VAL)
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_GETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
    EOS = 1
    DO
      IF (OPTION_VAL(EOS:EOS) .EQ. C_NULL_CHAR .OR. EOS .GE. OPTION_LEN) THEN
        EXIT
      END IF
      EOS = EOS + 1
    END DO
    EOS = EOS - 1
    OPTION_VALUE = OPTION_VAL(1:EOS)
    DEALLOCATE(OPTION_VAL)
  END FUNCTION ZMQ_GETSOCKOPT_STR

  FUNCTION ZMQ_SETSOCKOPT_INT(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    INTEGER(KIND = C_INT), TARGET :: OPTION_VAL

    OPTION_VAL = OPTION_VALUE
    OPTION_LEN = C_SIZEOF(OPTION_VAL)
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_SETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
  END FUNCTION ZMQ_SETSOCKOPT_INT

  FUNCTION ZMQ_SETSOCKOPT_INT64(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    INTEGER(KIND = C_INT64_T), VALUE, INTENT(IN) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    INTEGER(KIND = C_INT64_T), TARGET :: OPTION_VAL

    OPTION_VAL = OPTION_VALUE
    OPTION_LEN = C_SIZEOF(OPTION_VAL)
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_SETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
  END FUNCTION ZMQ_SETSOCKOPT_INT64

  FUNCTION ZMQ_SETSOCKOPT_STR(SOCKET, OPTION_NAME, OPTION_VALUE) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: OPTION_NAME
    CHARACTER(LEN = *), INTENT(IN) :: OPTION_VALUE
    INTEGER(KIND = C_INT) :: CODE

    TYPE(C_PTR) :: OPTION_PTR
    INTEGER(KIND = C_SIZE_T) :: OPTION_LEN
    CHARACTER(LEN = :), ALLOCATABLE, TARGET :: OPTION_VAL

    OPTION_LEN = LEN(TRIM(OPTION_VALUE)) + 1
    ALLOCATE(CHARACTER(LEN = OPTION_LEN) :: OPTION_VAL)
    OPTION_VAL = OPTION_VALUE(1:OPTION_LEN - 1) // C_NULL_CHAR
    OPTION_PTR = C_LOC(OPTION_VAL)
    CODE = FZMQ_SETSOCKOPT(SOCKET, OPTION_NAME, OPTION_PTR, OPTION_LEN)
    DEALLOCATE(OPTION_VAL)
  END FUNCTION ZMQ_SETSOCKOPT_STR

  FUNCTION ZMQ_STRERROR(ERRNUM) RESULT(MESSAGE)
    INTEGER(KIND = C_INT), VALUE, INTENT(IN) :: ERRNUM
    CHARACTER(LEN = :), ALLOCATABLE :: MESSAGE

    INTEGER :: SIZE
    TYPE(C_PTR) :: MSG_C_PTR
    CHARACTER(KIND = C_CHAR, LEN = :), POINTER :: MSG_PTR

    SIZE = 1
    MSG_C_PTR = FZMQ_STRERROR(ERRNUM)
    CALL C_F_POINTER(MSG_C_PTR, MSG_PTR)
    DO
      IF (MSG_PTR(SIZE:SIZE) .EQ. C_NULL_CHAR .OR. SIZE .GE. 64) THEN
        EXIT
      END IF
      SIZE = SIZE + 1
    END DO
    ALLOCATE(CHARACTER(KIND = C_CHAR, LEN = SIZE) :: MESSAGE)
    MESSAGE = TRANSFER(MSG_PTR(1:SIZE), MESSAGE)
  END FUNCTION ZMQ_STRERROR

  FUNCTION ZMQ_UNBIND(SOCKET, ENDPOINT) RESULT(CODE)
    TYPE(C_PTR), VALUE, INTENT(IN) :: SOCKET
    CHARACTER(LEN = *), INTENT(IN) :: ENDPOINT
    INTEGER(KIND = C_INT) :: CODE

    CODE = FZMQ_UNBIND(SOCKET, TRIM(ENDPOINT) // C_NULL_CHAR)
  END FUNCTION ZMQ_UNBIND

END MODULE ZMQ
